# Generated by Django 3.0.6 on 2021-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='Product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='User_id',
            field=models.IntegerField(),
        ),
    ]
