# Generated by Django 3.0.6 on 2021-03-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20210315_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='Recommendation_Id',
        ),
    ]
