# Generated by Django 3.0.6 on 2021-03-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('shape', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
        ),
    ]
